import { collection, addDoc, doc, setDoc, getDocs, writeBatch, Timestamp } from 'firebase/firestore';
import { db } from './firebase';

export async function seedDemoData() {
  try {
    const batch = writeBatch(db);

    // 2. Define Issues
    const demoIssues = [
  {
    id: 'mock_map_chandigarh_1',
    raw_input: 'Government School, Sector 12 area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 1,
    location_text: 'Government School, Sector 12, Chandigarh',
    location_coords: { lat: 30.74749, lng: 76.78651 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.8,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Chandigarh. Subject: SLA breach escalation for streetlight_broken reference #1. Reported unresolved at Government School, Sector 12, Chandigarh.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_1',
    zone: 'Sector 12',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_2',
    raw_input: 'Main Market Corner, Sector 15 area me: Sadak toot gayi hai aur vehicle nikalne me dikkat ho rahi hai. Please repair soon.',
    category: 'road_damage',
    severity: 2,
    location_text: 'Main Market Corner, Sector 15, Chandigarh',
    location_coords: { lat: 30.72254, lng: 76.76597 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.4,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_2',
    zone: 'Sector 15',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_3',
    raw_input: 'Market Parking Area, Sector 22 area me: Bada gaddha hai, accident hone ka darr hai. Please repair soon.',
    category: 'pothole',
    severity: 3,
    location_text: 'Market Parking Area, Sector 22, Chandigarh',
    location_coords: { lat: 30.74611, lng: 76.77495 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.4,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_3',
    zone: 'Sector 22',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_4',
    raw_input: 'Outer Circular Road, Sector 35-B area me: Sadak par building ka malba fenka gaya hai. Please repair soon.',
    category: 'illegal_construction',
    severity: 4,
    location_text: 'Outer Circular Road, Sector 35-B, Chandigarh',
    location_coords: { lat: 30.74369, lng: 76.77953 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.4,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Chandigarh. Subject: SLA breach escalation for illegal_construction reference #4. Reported unresolved at Outer Circular Road, Sector 35-B, Chandigarh.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_4',
    zone: 'Sector 35-B',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_5',
    raw_input: 'Avenue Road, Sector 8 area me: Ped gir gaya hai aur rasta block ho gaya hai. Please repair soon.',
    category: 'tree_fallen',
    severity: 5,
    location_text: 'Avenue Road, Sector 8, Chandigarh',
    location_coords: { lat: 30.74034, lng: 76.76999 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.9,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_5',
    zone: 'Sector 8',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_6',
    raw_input: 'Library Intersection, Sector 34 area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 1,
    location_text: 'Library Intersection, Sector 34, Chandigarh',
    location_coords: { lat: 30.74566, lng: 76.78121 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.4,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_6',
    zone: 'Sector 34',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_7',
    raw_input: 'Shopping Plaza, Sector 17 area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 2,
    location_text: 'Shopping Plaza, Sector 17, Chandigarh',
    location_coords: { lat: 30.7475, lng: 76.77177 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 6.3,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Chandigarh. Subject: SLA breach escalation for water_leak reference #7. Reported unresolved at Shopping Plaza, Sector 17, Chandigarh.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_7',
    zone: 'Sector 17',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_8',
    raw_input: 'Industrial Area Road, Sector 26 area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 3,
    location_text: 'Industrial Area Road, Sector 26, Chandigarh',
    location_coords: { lat: 30.72608, lng: 76.77719 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 6.7,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_8',
    zone: 'Sector 26',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_9',
    raw_input: 'Interstate Bus Terminal, Sector 43 area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 4,
    location_text: 'Interstate Bus Terminal, Sector 43, Chandigarh',
    location_coords: { lat: 30.72695, lng: 76.78899 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.3,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_9',
    zone: 'Sector 43',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_chandigarh_10',
    raw_input: 'Residential Boulevard, Sector 19 area me: Sadak toot gayi hai aur vehicle nikalne me dikkat ho rahi hai. Please repair soon.',
    category: 'road_damage',
    severity: 5,
    location_text: 'Residential Boulevard, Sector 19, Chandigarh',
    location_coords: { lat: 30.73416, lng: 76.78238 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.6,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Chandigarh. Subject: SLA breach escalation for road_damage reference #10. Reported unresolved at Residential Boulevard, Sector 19, Chandigarh.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_10',
    zone: 'Sector 19',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_1',
    raw_input: '100 Feet Road, Indiranagar area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 1,
    location_text: '100 Feet Road, Indiranagar, Bengaluru',
    location_coords: { lat: 12.96609, lng: 77.59695 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.5,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_11',
    zone: 'Indiranagar',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_2',
    raw_input: 'Sony World Signal, Koramangala area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 2,
    location_text: 'Sony World Signal, Koramangala, Bengaluru',
    location_coords: { lat: 12.96073, lng: 77.60399 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.6,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Bengaluru. Subject: SLA breach escalation for streetlight_broken reference #12. Reported unresolved at Sony World Signal, Koramangala, Bengaluru.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_12',
    zone: 'Koramangala',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_3',
    raw_input: 'ITPB Main Gate, Whitefield area me: Sadak toot gayi hai aur vehicle nikalne me dikkat ho rahi hai. Please repair soon.',
    category: 'road_damage',
    severity: 3,
    location_text: 'ITPB Main Gate, Whitefield, Bengaluru',
    location_coords: { lat: 12.9617, lng: 77.59473 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.2,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_13',
    zone: 'Whitefield',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_4',
    raw_input: 'Outer Ring Road Junction, HSR Layout area me: Bada gaddha hai, accident hone ka darr hai. Please repair soon.',
    category: 'pothole',
    severity: 4,
    location_text: 'Outer Ring Road Junction, HSR Layout, Bengaluru',
    location_coords: { lat: 12.97143, lng: 77.60201 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.1,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_14',
    zone: 'HSR Layout',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_5',
    raw_input: 'Metro Station Entrance, MG Road area me: Sadak par building ka malba fenka gaya hai. Please repair soon.',
    category: 'illegal_construction',
    severity: 5,
    location_text: 'Metro Station Entrance, MG Road, Bengaluru',
    location_coords: { lat: 12.95846, lng: 77.60472 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.3,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Bengaluru. Subject: SLA breach escalation for illegal_construction reference #15. Reported unresolved at Metro Station Entrance, MG Road, Bengaluru.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_15',
    zone: 'MG Road',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_6',
    raw_input: '8th Cross Road, Malleshwaram area me: Ped gir gaya hai aur rasta block ho gaya hai. Please repair soon.',
    category: 'tree_fallen',
    severity: 1,
    location_text: '8th Cross Road, Malleshwaram, Bengaluru',
    location_coords: { lat: 12.98248, lng: 77.60413 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.3,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_16',
    zone: 'Malleshwaram',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_7',
    raw_input: '4th Block Complex, Jayanagar area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 2,
    location_text: '4th Block Complex, Jayanagar, Bengaluru',
    location_coords: { lat: 12.96148, lng: 77.60467 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.5,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_17',
    zone: 'Jayanagar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_8',
    raw_input: 'Phase 1 Flyover Exit, Electronic City area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 3,
    location_text: 'Phase 1 Flyover Exit, Electronic City, Bengaluru',
    location_coords: { lat: 12.98508, lng: 77.60343 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.4,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Bengaluru. Subject: SLA breach escalation for water_leak reference #18. Reported unresolved at Phase 1 Flyover Exit, Electronic City, Bengaluru.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_18',
    zone: 'Electronic City',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_9',
    raw_input: 'Bashyam Circle, Sadashivanagar area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 4,
    location_text: 'Bashyam Circle, Sadashivanagar, Bengaluru',
    location_coords: { lat: 12.97198, lng: 77.59628 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.7,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_19',
    zone: 'Sadashivanagar',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_bengaluru_10',
    raw_input: 'Water Tank Junction, BTM Layout area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 5,
    location_text: 'Water Tank Junction, BTM Layout, Bengaluru',
    location_coords: { lat: 12.96289, lng: 77.58109 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.1,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_20',
    zone: 'BTM Layout',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_1',
    raw_input: 'Bus Stand Road, Swargate area me: Bada gaddha hai, accident hone ka darr hai. Please repair soon.',
    category: 'pothole',
    severity: 1,
    location_text: 'Bus Stand Road, Swargate, Pune',
    location_coords: { lat: 18.51818, lng: 73.85957 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.5,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Pune. Subject: SLA breach escalation for pothole reference #21. Reported unresolved at Bus Stand Road, Swargate, Pune.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_21',
    zone: 'Swargate',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_2',
    raw_input: 'Karve Road Circle, Kothrud area me: Sadak par building ka malba fenka gaya hai. Please repair soon.',
    category: 'illegal_construction',
    severity: 2,
    location_text: 'Karve Road Circle, Kothrud, Pune',
    location_coords: { lat: 18.51337, lng: 73.8464 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 6.2,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_22',
    zone: 'Kothrud',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_3',
    raw_input: 'Good Luck Cafe Junction, Deccan Gymkhana area me: Ped gir gaya hai aur rasta block ho gaya hai. Please repair soon.',
    category: 'tree_fallen',
    severity: 3,
    location_text: 'Good Luck Cafe Junction, Deccan Gymkhana, Pune',
    location_coords: { lat: 18.51878, lng: 73.86411 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 6.7,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_23',
    zone: 'Deccan Gymkhana',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_4',
    raw_input: 'Symbiosis Road, Viman Nagar area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 4,
    location_text: 'Symbiosis Road, Viman Nagar, Pune',
    location_coords: { lat: 18.52307, lng: 73.85289 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.8,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Pune. Subject: SLA breach escalation for drain_blocked reference #24. Reported unresolved at Symbiosis Road, Viman Nagar, Pune.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_24',
    zone: 'Viman Nagar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_5',
    raw_input: 'Phase 2 IT Park Corridor, Hinjewadi area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 5,
    location_text: 'Phase 2 IT Park Corridor, Hinjewadi, Pune',
    location_coords: { lat: 18.52386, lng: 73.8511 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.7,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_25',
    zone: 'Hinjewadi',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_6',
    raw_input: 'District Court Metro Gate, Shivajinagar area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 1,
    location_text: 'District Court Metro Gate, Shivajinagar, Pune',
    location_coords: { lat: 18.51119, lng: 73.84411 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.8,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_26',
    zone: 'Shivajinagar',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_7',
    raw_input: 'High Street Outer Lane, Baner area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 2,
    location_text: 'High Street Outer Lane, Baner, Pune',
    location_coords: { lat: 18.50888, lng: 73.84234 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.9,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Pune. Subject: SLA breach escalation for streetlight_broken reference #27. Reported unresolved at High Street Outer Lane, Baner, Pune.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_27',
    zone: 'Baner',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_8',
    raw_input: 'Bremen Circle, Aundh area me: Sadak toot gayi hai aur vehicle nikalne me dikkat ho rahi hai. Please repair soon.',
    category: 'road_damage',
    severity: 3,
    location_text: 'Bremen Circle, Aundh, Pune',
    location_coords: { lat: 18.50801, lng: 73.86804 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.1,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_28',
    zone: 'Aundh',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_9',
    raw_input: 'Magarpatta Bypass, Hadapsar area me: Bada gaddha hai, accident hone ka darr hai. Please repair soon.',
    category: 'pothole',
    severity: 4,
    location_text: 'Magarpatta Bypass, Hadapsar, Pune',
    location_coords: { lat: 18.52698, lng: 73.84445 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.0,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_29',
    zone: 'Hadapsar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_pune_10',
    raw_input: 'Joggers Park Corner, Kalyani Nagar area me: Sadak par building ka malba fenka gaya hai. Please repair soon.',
    category: 'illegal_construction',
    severity: 5,
    location_text: 'Joggers Park Corner, Kalyani Nagar, Pune',
    location_coords: { lat: 18.51715, lng: 73.8649 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.4,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Pune. Subject: SLA breach escalation for illegal_construction reference #30. Reported unresolved at Joggers Park Corner, Kalyani Nagar, Pune.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_30',
    zone: 'Kalyani Nagar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_1',
    raw_input: 'Central Park Outer Lane, C-Scheme area me: Ped gir gaya hai aur rasta block ho gaya hai. Please repair soon.',
    category: 'tree_fallen',
    severity: 1,
    location_text: 'Central Park Outer Lane, C-Scheme, Jaipur',
    location_coords: { lat: 26.91639, lng: 75.80129 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.0,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_31',
    zone: 'C-Scheme',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_2',
    raw_input: 'GT Mall Crossing, Malviya Nagar area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 2,
    location_text: 'GT Mall Crossing, Malviya Nagar, Jaipur',
    location_coords: { lat: 26.90809, lng: 75.79038 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.8,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Jaipur. Subject: SLA breach escalation for drain_blocked reference #32. Reported unresolved at GT Mall Crossing, Malviya Nagar, Jaipur.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_32',
    zone: 'Malviya Nagar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_3',
    raw_input: 'Amrapali Marg, Vaishali Nagar area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 3,
    location_text: 'Amrapali Marg, Vaishali Nagar, Jaipur',
    location_coords: { lat: 26.9246, lng: 75.7748 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.5,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_33',
    zone: 'Vaishali Nagar',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_4',
    raw_input: 'Metro Station Depot, Mansarovar area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 4,
    location_text: 'Metro Station Depot, Mansarovar, Jaipur',
    location_coords: { lat: 26.92169, lng: 75.78681 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.7,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_34',
    zone: 'Mansarovar',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_5',
    raw_input: 'Gali Number 3, Raja Park area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 5,
    location_text: 'Gali Number 3, Raja Park, Jaipur',
    location_coords: { lat: 26.92391, lng: 75.78441 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.1,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Jaipur. Subject: SLA breach escalation for streetlight_broken reference #35. Reported unresolved at Gali Number 3, Raja Park, Jaipur.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_35',
    zone: 'Raja Park',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_6',
    raw_input: 'Elevated Road Entry Pillar, Sodala area me: Sadak toot gayi hai aur vehicle nikalne me dikkat ho rahi hai. Please repair soon.',
    category: 'road_damage',
    severity: 1,
    location_text: 'Elevated Road Entry Pillar, Sodala, Jaipur',
    location_coords: { lat: 26.91891, lng: 75.7797 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.2,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_36',
    zone: 'Sodala',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_7',
    raw_input: 'Collectorate Road, Bani Park area me: Bada gaddha hai, accident hone ka darr hai. Please repair soon.',
    category: 'pothole',
    severity: 2,
    location_text: 'Collectorate Road, Bani Park, Jaipur',
    location_coords: { lat: 26.91381, lng: 75.77694 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.9,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_37',
    zone: 'Bani Park',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_8',
    raw_input: 'Railway Flyover Bridge, Jagatpura area me: Sadak par building ka malba fenka gaya hai. Please repair soon.',
    category: 'illegal_construction',
    severity: 3,
    location_text: 'Railway Flyover Bridge, Jagatpura, Jaipur',
    location_coords: { lat: 26.92385, lng: 75.79836 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.3,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Jaipur. Subject: SLA breach escalation for illegal_construction reference #38. Reported unresolved at Railway Flyover Bridge, Jagatpura, Jaipur.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_38',
    zone: 'Jagatpura',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_9',
    raw_input: 'Choti Chaupar Corner, Tonk Road area me: Ped gir gaya hai aur rasta block ho gaya hai. Please repair soon.',
    category: 'tree_fallen',
    severity: 4,
    location_text: 'Choti Chaupar Corner, Tonk Road, Jaipur',
    location_coords: { lat: 26.92307, lng: 75.78812 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.8,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_39',
    zone: 'Tonk Road',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_jaipur_10',
    raw_input: 'Raj Bhavan Outer Perimeter, Civil Lines area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 5,
    location_text: 'Raj Bhavan Outer Perimeter, Civil Lines, Jaipur',
    location_coords: { lat: 26.9165, lng: 75.79414 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.6,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_40',
    zone: 'Civil Lines',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_1',
    raw_input: 'Greenwood Public School, Sector 45 area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 1,
    location_text: 'Greenwood Public School, Sector 45, Gurgaon',
    location_coords: { lat: 28.4529, lng: 77.04158 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.7,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Gurgaon. Subject: SLA breach escalation for drain_blocked reference #41. Reported unresolved at Greenwood Public School, Sector 45, Gurgaon.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_41',
    zone: 'Sector 45',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_2',
    raw_input: 'U-Block Lane 12, DLF Phase 3 area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 2,
    location_text: 'U-Block Lane 12, DLF Phase 3, Gurgaon',
    location_coords: { lat: 28.46949, lng: 77.01873 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 6.2,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_42',
    zone: 'DLF Phase 3',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_3',
    raw_input: 'Rapid Metro Pillar 42, Golf Course Road area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 3,
    location_text: 'Rapid Metro Pillar 42, Golf Course Road, Gurgaon',
    location_coords: { lat: 28.47356, lng: 77.02014 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.5,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_43',
    zone: 'Golf Course Road',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_4',
    raw_input: 'Subhash Chowk Flyover, Sohna Road area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 4,
    location_text: 'Subhash Chowk Flyover, Sohna Road, Gurgaon',
    location_coords: { lat: 28.46676, lng: 77.04003 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.7,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Gurgaon. Subject: SLA breach escalation for streetlight_broken reference #44. Reported unresolved at Subhash Chowk Flyover, Sohna Road, Gurgaon.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_44',
    zone: 'Sohna Road',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_5',
    raw_input: 'Huda Market Plaza, Sector 56 area me: Sadak toot gayi hai aur vehicle nikalne me dikkat ho rahi hai. Please repair soon.',
    category: 'road_damage',
    severity: 5,
    location_text: 'Huda Market Plaza, Sector 56, Gurgaon',
    location_coords: { lat: 28.45549, lng: 77.03622 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.3,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_45',
    zone: 'Sector 56',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_6',
    raw_input: 'Cyber Hub Back Entrance, Cyber City area me: Bada gaddha hai, accident hone ka darr hai. Please repair soon.',
    category: 'pothole',
    severity: 1,
    location_text: 'Cyber Hub Back Entrance, Cyber City, Gurgaon',
    location_coords: { lat: 28.44685, lng: 77.03243 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.5,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_46',
    zone: 'Cyber City',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_7',
    raw_input: 'Leisure Valley Outer Gate, Sector 29 area me: Sadak par building ka malba fenka gaya hai. Please repair soon.',
    category: 'illegal_construction',
    severity: 2,
    location_text: 'Leisure Valley Outer Gate, Sector 29, Gurgaon',
    location_coords: { lat: 28.46712, lng: 77.03504 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.6,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Gurgaon. Subject: SLA breach escalation for illegal_construction reference #47. Reported unresolved at Leisure Valley Outer Gate, Sector 29, Gurgaon.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_47',
    zone: 'Sector 29',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_8',
    raw_input: 'Carterpuri Road Junction, Palam Vihar area me: Ped gir gaya hai aur rasta block ho gaya hai. Please repair soon.',
    category: 'tree_fallen',
    severity: 3,
    location_text: 'Carterpuri Road Junction, Palam Vihar, Gurgaon',
    location_coords: { lat: 28.45033, lng: 77.02636 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.0,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_48',
    zone: 'Palam Vihar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_9',
    raw_input: 'Phase 5 Highway Exit, Udyog Vihar area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 4,
    location_text: 'Phase 5 Highway Exit, Udyog Vihar, Gurgaon',
    location_coords: { lat: 28.46765, lng: 77.02617 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.2,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_49',
    zone: 'Udyog Vihar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_gurgaon_10',
    raw_input: 'Vatika Crossing, Sector 82 area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 5,
    location_text: 'Vatika Crossing, Sector 82, Gurgaon',
    location_coords: { lat: 28.47092, lng: 77.02673 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.3,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Gurgaon. Subject: SLA breach escalation for water_leak reference #50. Reported unresolved at Vatika Crossing, Sector 82, Gurgaon.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_50',
    zone: 'Sector 82',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_1',
    raw_input: 'Mussoorie Diversion, Rajpur Road area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 1,
    location_text: 'Mussoorie Diversion, Rajpur Road, Dehradun',
    location_coords: { lat: 30.33071, lng: 78.02144 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.7,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_51',
    zone: 'Rajpur Road',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_2',
    raw_input: 'Subharti Hospital Gate, Clement Town area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 2,
    location_text: 'Subharti Hospital Gate, Clement Town, Dehradun',
    location_coords: { lat: 30.32128, lng: 78.01962 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 6.0,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_52',
    zone: 'Clement Town',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_3',
    raw_input: 'DAV College Road, Karanpur area me: Streetlight kharab hai aur raat ko andhera rehta hai. Please repair soon.',
    category: 'streetlight_broken',
    severity: 3,
    location_text: 'DAV College Road, Karanpur, Dehradun',
    location_coords: { lat: 30.30558, lng: 78.03125 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.4,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Dehradun. Subject: SLA breach escalation for streetlight_broken reference #53. Reported unresolved at DAV College Road, Karanpur, Dehradun.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_53',
    zone: 'Karanpur',
    infrastructure_type: 'electricity',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_4',
    raw_input: 'Saharanpur Road Crossing, Patel Nagar area me: Sadak toot gayi hai aur vehicle nikalne me dikkat ho rahi hai. Please repair soon.',
    category: 'road_damage',
    severity: 4,
    location_text: 'Saharanpur Road Crossing, Patel Nagar, Dehradun',
    location_coords: { lat: 30.3163, lng: 78.02044 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 7.8,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_54',
    zone: 'Patel Nagar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_5',
    raw_input: 'IMA Perimeter Road, Premnagar area me: Bada gaddha hai, accident hone ka darr hai. Please repair soon.',
    category: 'pothole',
    severity: 5,
    location_text: 'IMA Perimeter Road, Premnagar, Dehradun',
    location_coords: { lat: 30.31364, lng: 78.0377 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.4,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_55',
    zone: 'Premnagar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_6',
    raw_input: 'Maharana Pratap Complex, Vasant Vihar area me: Sadak par building ka malba fenka gaya hai. Please repair soon.',
    category: 'illegal_construction',
    severity: 1,
    location_text: 'Maharana Pratap Complex, Vasant Vihar, Dehradun',
    location_coords: { lat: 30.32026, lng: 78.02286 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 4.5,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Dehradun. Subject: SLA breach escalation for illegal_construction reference #56. Reported unresolved at Maharana Pratap Complex, Vasant Vihar, Dehradun.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_56',
    zone: 'Vasant Vihar',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_7',
    raw_input: 'EC Road Intersection, Dalanwala area me: Ped gir gaya hai aur rasta block ho gaya hai. Please repair soon.',
    category: 'tree_fallen',
    severity: 2,
    location_text: 'EC Road Intersection, Dalanwala, Dehradun',
    location_coords: { lat: 30.30924, lng: 78.04495 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 5.7,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_57',
    zone: 'Dalanwala',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_8',
    raw_input: 'Chowk Circle, Ballupur area me: Nala block ho gaya hai aur paani bhad raha hai. Please repair soon.',
    category: 'drain_blocked',
    severity: 3,
    location_text: 'Chowk Circle, Ballupur, Dehradun',
    location_coords: { lat: 30.32963, lng: 78.02371 },
    status: 'open',
    created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 6.6,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_58',
    zone: 'Ballupur',
    infrastructure_type: 'road',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_9',
    raw_input: 'Pacific Mall Outer Lane, Jakhan area me: Paani ki pipe tootne se paani waste ho raha hai. Please repair soon.',
    category: 'water_leak',
    severity: 4,
    location_text: 'Pacific Mall Outer Lane, Jakhan, Dehradun',
    location_coords: { lat: 30.32476, lng: 78.03422 },
    status: 'escalated',
    created_at: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 8.7,
    escalation_letter_drafted: true,
    escalation_letter: 'To Nodal Officer, municipal body in Dehradun. Subject: SLA breach escalation for water_leak reference #59. Reported unresolved at Pacific Mall Outer Lane, Jakhan, Dehradun.',
    ledger_published: true,
    reporter_uid: 'demo_reporter_59',
    zone: 'Jakhan',
    infrastructure_type: 'water',
    language_detected: 'hi'
  },
  {
    id: 'mock_map_dehradun_10',
    raw_input: 'Sulphur Spring Approach Road, Sahastradhara Road area me: Kachra patra bhar gaya hai aur gandagi phaili hui hai. Please repair soon.',
    category: 'garbage_dump',
    severity: 5,
    location_text: 'Sulphur Spring Approach Road, Sahastradhara Road, Dehradun',
    location_coords: { lat: 30.30902, lng: 78.02006 },
    status: 'resolved',
    created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    sla_deadline: Timestamp.fromDate(new Date(Date.now() + -1 * 24 * 60 * 60 * 1000)),
    updated_at: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    cluster_id: null,
    coi_score: 9.3,
    escalation_letter_drafted: false,
    ledger_published: true,
    reporter_uid: 'demo_reporter_60',
    zone: 'Sahastradhara Road',
    infrastructure_type: 'waste',
    language_detected: 'hi'
  }
];

    // 3. Define Clusters
    const demoClusters = [
      {
        id: 'demo_cluster_1',
        zone: 'Sector 12',
        issue_type: 'water_leak',
        member_issue_ids: ['demo_issue_1'],
        total_reports: 3,
        avg_severity: 4.7,
        coi_estimate: 85,
        risk_level: 'high',
        pattern_description: 'Recurrent leakage in major municipal supply pipeline near school zones. High public consequence.',
        risk_geojson: {
          type: 'Feature',
          geometry: {
            type: 'Polygon',
            coordinates: [[
              [76.764, 30.762],
              [76.773, 30.762],
              [76.773, 30.755],
              [76.764, 30.755],
              [76.764, 30.762]
            ]]
          }
        },
        created_at: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
        updated_at: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000))
      },
      {
        id: 'demo_cluster_2',
        zone: 'Sector 22',
        issue_type: 'garbage_dump',
        member_issue_ids: ['demo_issue_3'],
        total_reports: 5,
        avg_severity: 4.0,
        coi_estimate: 70,
        risk_level: 'medium',
        pattern_description: 'Commercial collection backlog in dense market sector. Poses sanitary hazards.',
        risk_geojson: {
          type: 'Feature',
          geometry: {
            type: 'Polygon',
            coordinates: [[
              [76.755, 30.742],
              [76.766, 30.742],
              [76.766, 30.733],
              [76.755, 30.733],
              [76.755, 30.742]
            ]]
          }
        },
        created_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
        updated_at: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000))
      }
    ];

    // 4. Define Ledger events
    const demoLedger = [
      {
        id: 'demo_ledger_1',
        issue_id: 'demo_issue_1',
        event_type: 'submitted',
        timestamp: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
        description: 'New water leak report classified in Sector 12. Triage Agent set SLA clock to 24h.',
        actor: 'system',
        is_public: true
      },
      {
        id: 'demo_ledger_2',
        issue_id: 'demo_issue_1',
        event_type: 'escalated',
        timestamp: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
        description: 'SLA Watchdog detected unresolved critical leak past 24h deadline. Formally escalated to Chief Engineer.',
        actor: 'system',
        metadata: {
          letter_preview: 'Subject: Escalation of unresolved water leak under SLA reference #DE1. Water leakage near Government High School, Sector 12 has breached SLA limit...'
        },
        is_public: true
      },
      {
        id: 'demo_ledger_3',
        issue_id: 'demo_issue_2',
        event_type: 'submitted',
        timestamp: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
        description: 'Streetlight outage ticket initialized in Sector 15. Assigned to Electricity Maintenance Division.',
        actor: 'system',
        is_public: true
      },
      {
        id: 'demo_ledger_4',
        issue_id: 'demo_issue_3',
        event_type: 'submitted',
        timestamp: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
        description: 'Commercial waste overflow ticket registered in Sector 22 market zone.',
        actor: 'system',
        is_public: true
      },
      {
        id: 'demo_ledger_5',
        issue_id: 'demo_issue_4',
        event_type: 'submitted',
        timestamp: Timestamp.fromDate(new Date(Date.now() - 6 * 24 * 60 * 60 * 1000)),
        description: 'Sector 35 road pothole complaint registered via photo submission.',
        actor: 'system',
        is_public: true
      },
      {
        id: 'demo_ledger_6',
        issue_id: 'demo_issue_4',
        event_type: 'verified',
        timestamp: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
        description: 'Verification Agent reviewed resolution photo. Confirmed pothole filled and road surface restored.',
        actor: 'system',
        metadata: {
          verdict: 'VERIFIED',
          confidence: 0.94,
          visible_changes: 'Verified: Pothole filled with black bitumen aggregate. Level surface restored.'
        },
        is_public: true
      }
    ];

    // Add to Batch writes
    demoIssues.forEach(issue => {
      const { id, ...data } = issue;
      batch.set(doc(db, 'issues', id), data);
    });

    demoClusters.forEach(cluster => {
      const { id, ...data } = cluster;
      batch.set(doc(db, 'clusters', id), data);
    });

    demoLedger.forEach(item => {
      const { id, ...data } = item;
      batch.set(doc(db, 'ledger', id), data);
    });

    await batch.commit();
    return { success: true, message: 'Demo environment initialized with geocoded reports, risk clusters, and audit ledger!' };
  } catch (err) {
    console.error('Seeding error:', err);
    return { success: false, message: 'Failed to seed demo data: ' + err.message };
  }
}
